// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cafefinder.database;

#nullable disable

namespace cafefinder.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20240903121723_coments")]
    partial class coments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cafefinder.database.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BirthdayTheme")
                        .HasColumnType("bit");

                    b.Property<bool>("BookCafe")
                        .HasColumnType("bit");

                    b.Property<bool>("CafeShop")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FoodAndDrink")
                        .HasColumnType("bit");

                    b.Property<string>("FreeSittingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FreeSmoke")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OpenSpace")
                        .HasColumnType("bit");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Restaurant")
                        .HasColumnType("bit");

                    b.Property<bool>("RoofGarden")
                        .HasColumnType("bit");

                    b.Property<string>("StarRating")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = new Guid("780c7e29-bcb3-4b8f-a5bf-8b6ec167920d"),
                            Address = "بلوار سجاد، پاساژ لاله ، انتهای پاساژ طبقه اول",
                            BirthdayTheme = false,
                            BookCafe = true,
                            CafeShop = true,
                            City = "mashhad",
                            FoodAndDrink = false,
                            FreeSittingTime = "45 min",
                            FreeSmoke = true,
                            Link = "www.mrk.co.ir",
                            LocationLink = "www.mrk.co.ir",
                            Name = "ماه من",
                            Neighborhood = "سجاد",
                            OpenSpace = true,
                            Photo = "[]",
                            Restaurant = false,
                            RoofGarden = true,
                            StarRating = "{}"
                        },
                        new
                        {
                            Id = new Guid("932fc171-3c85-44a5-a86f-de7be3d544cb"),
                            Address = "بلوار سجاد ،چهارراه گلریز ، گلریز4،یاس3",
                            BirthdayTheme = false,
                            BookCafe = true,
                            CafeShop = true,
                            City = "mashhad",
                            FoodAndDrink = true,
                            FreeSittingTime = "free time",
                            FreeSmoke = true,
                            Link = "www.miranagency.ir",
                            LocationLink = "www.miranagency.ir",
                            Name = "خانه اکنون",
                            Neighborhood = "سجاد",
                            OpenSpace = true,
                            Photo = "[]",
                            Restaurant = true,
                            RoofGarden = false,
                            StarRating = "{}"
                        },
                        new
                        {
                            Id = new Guid("6b797993-efe1-46fa-a18d-070f31509655"),
                            Address = "وکیل آباد 13",
                            BirthdayTheme = false,
                            BookCafe = false,
                            CafeShop = false,
                            City = "mashhad",
                            FoodAndDrink = false,
                            FreeSittingTime = "free time",
                            FreeSmoke = false,
                            Link = "www.miranagency.ir",
                            LocationLink = "www.miranagency.ir",
                            Name = " لیالی لبنان",
                            Neighborhood = "وکیل آباد",
                            OpenSpace = true,
                            Photo = "[]",
                            Restaurant = true,
                            RoofGarden = false,
                            StarRating = "{}"
                        });
                });

            modelBuilder.Entity("cafefinder.database.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numberphone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
