// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cafefinder.database;

#nullable disable

namespace cafefinder.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20240908122935_addusernameplace")]
    partial class addusernameplace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cafefinder.database.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BirthdayTheme")
                        .HasColumnType("bit");

                    b.Property<bool>("BookCafe")
                        .HasColumnType("bit");

                    b.Property<bool>("CafeShop")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FoodAndDrink")
                        .HasColumnType("bit");

                    b.Property<string>("FreeSittingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FreeSmoke")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OpenSpace")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Restaurant")
                        .HasColumnType("bit");

                    b.Property<bool>("RoofGarden")
                        .HasColumnType("bit");

                    b.Property<string>("StarRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rezarv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = new Guid("92f37ab2-cc03-4f13-8a8f-1ce8d78937d2"),
                            Address = "بلوار سجاد، پاساژ لاله ، انتهای پاساژ طبقه اول",
                            BirthdayTheme = false,
                            BookCafe = true,
                            CafeShop = true,
                            City = "mashhad",
                            FoodAndDrink = false,
                            FreeSittingTime = "45 min",
                            FreeSmoke = true,
                            Link = "www.mrk.co.ir",
                            LocationLink = "www.mrk.co.ir",
                            Name = "ماه من",
                            Neighborhood = "سجاد",
                            OpenSpace = true,
                            Password = "Password",
                            Photo = "[]",
                            Restaurant = false,
                            RoofGarden = true,
                            StarRating = "[]",
                            UserName = "my-moon",
                            rezarv = "{}"
                        },
                        new
                        {
                            Id = new Guid("4b0c979f-7e86-4fa9-a93a-cd706790cb69"),
                            Address = "بلوار سجاد ،چهارراه گلریز ، گلریز4،یاس3",
                            BirthdayTheme = false,
                            BookCafe = true,
                            CafeShop = true,
                            City = "mashhad",
                            FoodAndDrink = true,
                            FreeSittingTime = "free time",
                            FreeSmoke = true,
                            Link = "www.miranagency.ir",
                            LocationLink = "www.miranagency.ir",
                            Name = "خانه اکنون",
                            Neighborhood = "سجاد",
                            OpenSpace = true,
                            Password = "Password",
                            Photo = "[]",
                            Restaurant = true,
                            RoofGarden = false,
                            StarRating = "[]",
                            UserName = "aknon-home",
                            rezarv = "{}"
                        },
                        new
                        {
                            Id = new Guid("07d6aad7-0601-4495-85dc-9fb758c7806e"),
                            Address = "وکیل آباد 13",
                            BirthdayTheme = false,
                            BookCafe = false,
                            CafeShop = false,
                            City = "mashhad",
                            FoodAndDrink = false,
                            FreeSittingTime = "free time",
                            FreeSmoke = false,
                            Link = "www.miranagency.ir",
                            LocationLink = "www.miranagency.ir",
                            Name = " لیالی لبنان",
                            Neighborhood = "وکیل آباد",
                            OpenSpace = true,
                            Password = "Password",
                            Photo = "[]",
                            Restaurant = true,
                            RoofGarden = false,
                            StarRating = "[]",
                            UserName = "layali-lobnan",
                            rezarv = "{}"
                        });
                });

            modelBuilder.Entity("cafefinder.database.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numberphone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9afdb37-ce0f-42ad-acab-fa82f6521051"),
                            Numberphone = "09334101438",
                            Password = "cafe1403admin*",
                            UserName = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
