// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cafefinder.database;

#nullable disable

namespace cafefinder.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20240907075414_adduser")]
    partial class adduser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cafefinder.database.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BirthdayTheme")
                        .HasColumnType("bit");

                    b.Property<bool>("BookCafe")
                        .HasColumnType("bit");

                    b.Property<bool>("CafeShop")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FoodAndDrink")
                        .HasColumnType("bit");

                    b.Property<string>("FreeSittingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FreeSmoke")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OpenSpace")
                        .HasColumnType("bit");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Restaurant")
                        .HasColumnType("bit");

                    b.Property<bool>("RoofGarden")
                        .HasColumnType("bit");

                    b.Property<string>("StarRating")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c5e89a3-88e2-428e-9e6f-703f2f436d15"),
                            Address = "بلوار سجاد، پاساژ لاله ، انتهای پاساژ طبقه اول",
                            BirthdayTheme = false,
                            BookCafe = true,
                            CafeShop = true,
                            City = "mashhad",
                            FoodAndDrink = false,
                            FreeSittingTime = "45 min",
                            FreeSmoke = true,
                            Link = "www.mrk.co.ir",
                            LocationLink = "www.mrk.co.ir",
                            Name = "ماه من",
                            Neighborhood = "سجاد",
                            OpenSpace = true,
                            Photo = "[]",
                            Restaurant = false,
                            RoofGarden = true,
                            StarRating = "[]"
                        },
                        new
                        {
                            Id = new Guid("96c29506-4ddf-4698-a978-99319ca44903"),
                            Address = "بلوار سجاد ،چهارراه گلریز ، گلریز4،یاس3",
                            BirthdayTheme = false,
                            BookCafe = true,
                            CafeShop = true,
                            City = "mashhad",
                            FoodAndDrink = true,
                            FreeSittingTime = "free time",
                            FreeSmoke = true,
                            Link = "www.miranagency.ir",
                            LocationLink = "www.miranagency.ir",
                            Name = "خانه اکنون",
                            Neighborhood = "سجاد",
                            OpenSpace = true,
                            Photo = "[]",
                            Restaurant = true,
                            RoofGarden = false,
                            StarRating = "[]"
                        },
                        new
                        {
                            Id = new Guid("75098651-364f-4b66-ad6f-650bec447fd7"),
                            Address = "وکیل آباد 13",
                            BirthdayTheme = false,
                            BookCafe = false,
                            CafeShop = false,
                            City = "mashhad",
                            FoodAndDrink = false,
                            FreeSittingTime = "free time",
                            FreeSmoke = false,
                            Link = "www.miranagency.ir",
                            LocationLink = "www.miranagency.ir",
                            Name = " لیالی لبنان",
                            Neighborhood = "وکیل آباد",
                            OpenSpace = true,
                            Photo = "[]",
                            Restaurant = true,
                            RoofGarden = false,
                            StarRating = "[]"
                        });
                });

            modelBuilder.Entity("cafefinder.database.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numberphone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("52491717-410f-4935-a76f-397bab619c75"),
                            Numberphone = "09334101438",
                            Password = "cafe1403admin*",
                            UserName = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
